version: "3.7"

services:
    frontend:
        image: training_frontend
        build:
            context: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
        ports:
            - 3000:3000
    
    backend:
        image: training_backend
        build:
            context: https://github.com/docker-hy/ml-kurkkumopo-backend.git
        ports:
            - 5000:5000
        volumes:
            - model:/src/model
        depends_on: 
            - training
    
    training:
        image: training
        build:
            context: https://github.com/docker-hy/ml-kurkkumopo-training.git
        volumes:
            - model:/src/model
            - imgs:/src/imgs
            - data:/src/data

volumes:
    imgs:
    data:
    model: