version: "3.7"

services:
    nginx-proxy:
        image: nginx:latest
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on: 
            - frontend
            - backend
        networks:
            - service-network

    frontend:
        image: frontend
        environment:
            - REACT_APP_BACKEND_URL=http://localhost/api/
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        networks:
            - service-network
        

    backend:
        image: backend
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        networks:
            - cache-network
            - database-network
            - service-network
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=P@ssW0rd
            - POSTGRES_DATABASE=postgres
            
    postgres:
        image: postgres:13.3
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: P@ssW0rd
        networks:
            - database-network
        volumes:
            - ./database:/var/lib/postgresql/data
        
    redis:
        image: redis:6.2.3
        networks:
            - cache-network
networks:
    cache-network:
        name: cache-network
    database-network:
        name: database-network
    service-network:
        name: service-network

volumes:
    database: